default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000

development:
  <<: *default
  database: brand_products_development

test:
  <<: *default
  database: brand_products_test

production:
  <<: *default
