all:
  - "Air Cleaner"
  - "Air Compressor"
  - "Air Conditioner"
  - "All in One Printer"
  - "Amplified Phone"
  - "Answering Machine"
  - "Appliance Trim Kit"
  - "Automobile"
  - "Automobile Accessories"
  - "Automobile Alarm"
  - "Automobile Battery Charger"
  - "Automobile Electronics"
  - "Automobile Parts"
  - "Baby Accessories"
  - "Baby Carrier"
  - "Baby Furniture"
  - "Baby Gym"
  - "Baby Jumper"
  - "Baby Monitor"
  - "Baby Playpen"
  - "Baby Swing"
  - "Baby Toy"
  - "Baby Walker"
  - "Backyard Playset"
  - "Barcode Reader"
  - "Bathroom Aids"
  - "Battery Charger"
  - "Beverage Dispenser"
  - "Bicycle"
  - "Bicycle Accessories"
  - "Bike Rack"
  - "Binding Machine"
  - "Binoculars"
  - "Biscuit Joiner"
  - "Blender"
  - "Blood Glucose Meter"
  - "Blood Pressure Monitor"
  - "Blower"
  - "Blowtorch"
  - "Blu-ray Player"
  - "Bluetooth Headset"
  - "Board Games"
  - "Boat"
  - "Boat Trailer"
  - "Boating Equipment"
  - "Boiler"
  - "Bottle Warmer"
  - "Bouncy Seat"
  - "Bread Maker"
  - "Breast Pump"
  - "Brush Cutter"
  - "Building Set"
  - "Burner"
  - "Cable Box"
  - "Calculator"
  - "Caller ID Box"
  - "Camcorder"
  - "Camcorder Accessories"
  - "Camera Accessories"
  - "Camera Flash"
  - "Camera Lens"
  - "Camper"
  - "Camping Equipment"
  - "Can Opener"
  - "Car Amplifier"
  - "Car Satellite Radio System"
  - "Car Satellite TV System"
  - "Car Seat"
  - "Car Speaker"
  - "Car Stereo System"
  - "Car Video System"
  - "Carbon Monoxide Alarm"
  - "Card Game"
  - "Carpet Cleaner"
  - "Carrying Case"
  - "Cash Register"
  - "Cassette Player"
  - "Caulking Gun"
  - "CD Player"
  - "Cell Phone"
  - "Cell Phone Accessories"
  - "Chainsaw"
  - "Chainsaw Sharpener"
  - "Charcoal Grill"
  - "Child Tracker"
  - "Chipper"
  - "Clock"
  - "Clock Radio"
  - "Clothes Dryer"
  - "Coffee Grinder"
  - "Coffeemaker"
  - "Compact Excavator"
  - "Compact Loader"
  - "Computer Accessories"
  - "Computer Drive"
  - "Computer Hardware"
  - "Computer Keyboard"
  - "Computer Monitor"
  - "Conference Phone"
  - "Convection Oven"
  - "Cooktop"
  - "Cookware"
  - "Copier"
  - "Corded Headset"
  - "Cordless Drill"
  - "Cordless Sander"
  - "Cordless Saw"
  - "Cordless Telephone"
  - "Credit Card Machine"
  - "Crepe Maker"
  - "Crib"
  - "Crib Toy"
  - "Cross Country Skier"
  - "CRT Television"
  - "Cultivator"
  - "Cyclometer"
  - "Decking"
  - "Dehumidifier"
  - "Digital Camera"
  - "Digital Photo Frame"
  - "Digital Photo Keychain"
  - "Dishwasher"
  - "DJ Equipment"
  - "Doll"
  - "Dollhouse"
  - "Door"
  - "Double Oven"
  - "Drill"
  - "Drums"
  - "Dryer Accessories"
  - "Dust Collector"
  - "DVD Player"
  - "DVD Recorder"
  - "DVD VCR Combo"
  - "DVR"
  - "eBook Reader"
  - "Edger"
  - "Egg Cooker"
  - "Electric Cookie Press"
  - "Electric Garlic Roaster"
  - "Electric Grill"
  - "Electric Heater"
  - "Electric Pencil Sharpener"
  - "Electric Pet Fence"
  - "Electric Pressure Cooker"
  - "Electric Shaver"
  - "Electric Steamer"
  - "Electric Toothbrush"
  - "Electronic Accessory"
  - "Electronic Keyboard"
  - "Elliptical Trainer"
  - "Engraver"
  - "Espresso Maker"
  - "Exercise Bike"
  - "Fan"
  - "Fax Machine"
  - "Film Camera"
  - "Fire Extinguisher"
  - "Fire Pit"
  - "Fish Finder"
  - "Fishing Equipment"
  - "Fitness Electronics"
  - "Fitness Equipment"
  - "Flash Memory"
  - "Flat Panel Television"
  - "Flooring"
  - "Fondue Maker"
  - "Food Processor"
  - "Food Saver"
  - "Food Warmer"
  - "Freezer"
  - "Frozen Dessert Maker"
  - "Fryer"
  - "Furnace"
  - "Games"
  - "Garage Door Opener"
  - "Garbage Disposal"
  - "Gas Grill"
  - "Gas Heater"
  - "Glue Gun"
  - "GPS Receiver"
  - "Graphics Tablet"
  - "Greenhouse Kit"
  - "Griddle"
  - "Grill Accessory"
  - "Grinder"
  - "Guitar"
  - "Hair Care Product"
  - "Hair Clippers"
  - "Hair Dryer"
  - "Handheld Game System"
  - "Handheld TV"
  - "Headphones"
  - "Hearing Aid"
  - "Heart Rate Monitor"
  - "Heat Gun"
  - "Heat Pump"
  - "Heating System"
  - "High Chair"
  - "Hiking Equipment"
  - "Home Care Product"
  - "Home Dialysis Equipment"
  - "Home Gym"
  - "Home Safety Product"
  - "Home Security System"
  - "Home Theater Screen"
  - "Home Theater Server"
  - "Home Theater System"
  - "Hot Beverage Maker"
  - "Hot Tub"
  - "Humidifier"
  - "Hunting Equipment"
  - "Ice Maker"
  - "Ice Tea Maker"
  - "Impact Driver"
  - "Indoor Fireplace"
  - "Indoor Furnishings"
  - "Inflatable Bouncy Toy"
  - "Insect Control Equipment"
  - "Insulin Pen"
  - "Intercom System"
  - "IP Phone"
  - "Iron"
  - "Irrigation System"
  - "Jet Ski"
  - "Juicer"
  - "Karaoke Machine"
  - "Kitchen Entertainment Center"
  - "Kitchen Grill"
  - "Kitchen Utensil"
  - "Label Maker"
  - "Laminate Trimmer"
  - "Laminator"
  - "Landscape Lighting"
  - "Laptop"
  - "Laptop Docking Station"
  - "Laser Level"
  - "Laser Pointer"
  - "Lathe"
  - "Lawn Aerator"
  - "Lawn Mower"
  - "Lawn Mower Accessory"
  - "Lawn Sweeper"
  - "Life Jacket"
  - "Light Therapy Device"
  - "Log Splitter"
  - "Lopper"
  - "Marine Battery"
  - "Marine GPS System"
  - "Marine Heating System"
  - "Marine Instruments"
  - "Marine Lighting"
  - "Marine RADAR"
  - "Marine Radio"
  - "Marine Safety Devices"
  - "Marine Sanitation System"
  - "Meat Grinder"
  - "Medical Alarms"
  - "Metal Detector"
  - "Microcassette Recorder"
  - "Microphone"
  - "Microscope & Magnifier"
  - "Microwave Oven"
  - "MiniDisc Player"
  - "Mixer"
  - "Mobility Aid"
  - "Mobility Scooter"
  - "Model Vehicle"
  - "Modem"
  - "Motor Scooter"
  - "Motorcycle"
  - "Motorcycle Accessories"
  - "Motorized Awning"
  - "Motorized Toy Car"
  - "Mouse"
  - "MP3 Docking Station"
  - "MP3 Player"
  - "MP3 Player Accessories"
  - "Multi-tool"
  - "Music Mixer"
  - "Music Pedal"
  - "Musical Instrument"
  - "Musical Instrument Amplifier"
  - "Musical Table"
  - "Musical Toy Instrument"
  - "Nail Gun"
  - "Nebulizer"
  - "Network Cables"
  - "Network Card"
  - "Network Hardware"
  - "Network Router"
  - "Noise Reduction Machine"
  - "Offroad Vehicle"
  - "Outboard Motor"
  - "Outdoor Cart"
  - "Outdoor Ceiling Fan"
  - "Outdoor Fireplace"
  - "Outdoor Fountain"
  - "Outdoor Gas Burner"
  - "Outdoor Grill Cover"
  - "Outdoor Kitchen Island"
  - "Outdoor Misting Fan"
  - "Outdoor Shower"
  - "Outdoor Storage"
  - "Outdoor Timer"
  - "Oven"
  - "Oven Accessories"
  - "Oxygen Equipment"
  - "Pacemaker"
  - "Pager"
  - "Paint Remover"
  - "Paint Sprayer"
  - "Paper Shredder"
  - "Pasta Maker"
  - "Patio Furniture"
  - "Patio Heater"
  - "Patio Umbrella"
  - "PDAs & Smartphones"
  - "Pedicure Spa"
  - "Personal Computer"
  - "Personal Lift"
  - "Pest Control Equipment"
  - "Pet Care Product"
  - "Pet Fence"
  - "Photo Printer"
  - "Photo Scanner"
  - "Picnic Table"
  - "Pill Reminder Device"
  - "Planer"
  - "Plumbing Product"
  - "Pole Saw"
  - "Popcorn Poppers"
  - "Portable CD Player"
  - "Portable DVD Player"
  - "Portable Generator"
  - "Portable Media Storage"
  - "Portable Multimedia Player"
  - "Portable Radio"
  - "Portable Speaker"
  - "Portable Stereo System"
  - "Postal Equipment"
  - "Power Hammer"
  - "Power Roller"
  - "Power Screwdriver"
  - "Power Supply"
  - "Pressure Washer"
  - "Printer"
  - "Printer Accessories"
  - "Projection Television"
  - "Projector"
  - "Projector Accessories"
  - "Quesadilla Maker"
  - "Radar Detector"
  - "Radio"
  - "Radio Antenna"
  - "Range"
  - "Recording Equipment"
  - "Refrigerator"
  - "Remote Starter"
  - "Respiratory Product"
  - "Rice Cooker"
  - "Riding Toy"
  - "Robotics"
  - "Router"
  - "Rowing Machine"
  - "Safety Gate"
  - "Sander"
  - "Satellite Radio"
  - "Satellite TV System"
  - "Saw"
  - "Scale"
  - "Scanner"
  - "Scuba Diving Equipment"
  - "Security Camera"
  - "Septic System"
  - "Server"
  - "Sewing Machine"
  - "Siding"
  - "Skin Care Product"
  - "Skis"
  - "Sleep Apnea Machine"
  - "Slow Cooker"
  - "Smoke Alarm"
  - "Smoker"
  - "Snow Blower"
  - "Snow Blower Attachment"
  - "Snowboard"
  - "Snowshoes"
  - "Soldering Gun"
  - "SONAR"
  - "Speaker"
  - "Speaker System"
  - "Spreader"
  - "Sprinkler"
  - "Staple Gun"
  - "Stepper Machine"
  - "Stereo Amplifier"
  - "Stereo Equalizer"
  - "Stereo Receiver"
  - "Stereo System"
  - "Stove"
  - "Stroller"
  - "Stud Sensor"
  - "Styling Iron"
  - "Surge Protector"
  - "Swimming Pool"
  - "Swimming Pool Filter"
  - "Swimming Pool Gate Alarm"
  - "Swimming Pool Heater"
  - "Swimming Pool Pump"
  - "Swimming Pool Vacuum"
  - "Swing Sets"
  - "Switch"
  - "Table Top Game"
  - "Tablet"
  - "Tablet Accessory"
  - "Telephone"
  - "Telephone Accessories"
  - "Telescope"
  - "Tent"
  - "Thermometer"
  - "Thermostat"
  - "Tiller"
  - "Time Clock"
  - "Toaster"
  - "Toddler Furniture"
  - "Tool Storage"
  - "Tortilla Maker"
  - "Trash Compactor"
  - "Treadmill"
  - "Trimmer"
  - "Turkey Fryer"
  - "Turntable"
  - "TV Antenna"
  - "TV Cables"
  - "TV Converter Box"
  - "TV DVD Combo"
  - "TV Mount"
  - "TV Receiver"
  - "TV VCR Combo"
  - "TV Video Accessories"
  - "Two-Way Radio"
  - "Typewriter"
  - "Ultrasonic Jewelry Cleaner"
  - "Universal Remote"
  - "Utility Trailer"
  - "Utility Vehicle"
  - "Vacuum Cleaner"
  - "VCR"
  - "Ventilation Hood"
  - "Video Eyeware"
  - "Video Game Console"
  - "Video Game Controller"
  - "Video Game Furniture"
  - "Video Game Headset"
  - "Video Game Keyboard"
  - "Video Game Sound System"
  - "Video Games"
  - "Video Gaming Accessories"
  - "Waffle Iron"
  - "Washer"
  - "Washer Accessories"
  - "Washer/Dryer"
  - "Watch"
  - "Water Dispenser"
  - "Water Heater"
  - "Water Pump"
  - "Water System"
  - "Waterskis"
  - "Weather Radio"
  - "Webcam"
  - "Welder"
  - "Welding Consumables"
  - "Welding System"
  - "Wheelchair"
  - "Whiteboard Accessories"
  - "Window"
  - "Wireless Office Headset"
  - "Wok"
  - "Work Light"
  - "Yard Vacuum"
  - "Yogurt Maker"

given:
  - "Audio System"
  - "Air Conditioner"
  - "Radio"
  - "Stove"
  - "Tablet"
  - "Fridge"
  - "Freezer"
  - "Microwave"
  - "Juicer"
  - "Toaster"
  - "Oven"
  - "Kettle"
  - "Electric Cooker"
  - "Coffee Machine"
  - "Mixer"
  - "Food Processor"
  - "Scanner"
  - "Projector"

matching:
  "Microwave":
    - "Microwave Oven"
  "Fridge":
    - "Refrigerator"
  "Coffee Machine":
    - "Coffeemaker"

