all:
  - name: "Air Cleaner"
  - name: "Air Compressor"
  - name: "Air Conditioner"
  - name: "All in One Printer"
  - name: "Amplified Phone"
  - name: "Answering Machine"
  - name: "Appliance Trim Kit"
  - name: "Automobile"
  - name: "Automobile Accessories"
  - name: "Automobile Alarm"
  - name: "Automobile Battery Charger"
  - name: "Automobile Electronics"
  - name: "Automobile Parts"
  - name: "Baby Accessories"
  - name: "Baby Carrier"
  - name: "Baby Furniture"
  - name: "Baby Gym"
  - name: "Baby Jumper"
  - name: "Baby Monitor"
  - name: "Baby Playpen"
  - name: "Baby Swing"
  - name: "Baby Toy"
  - name: "Baby Walker"
  - name: "Backyard Playset"
  - name: "Barcode Reader"
  - name: "Bathroom Aids"
  - name: "Battery Charger"
  - name: "Beverage Dispenser"
  - name: "Bicycle"
  - name: "Bicycle Accessories"
  - name: "Bike Rack"
  - name: "Binding Machine"
  - name: "Binoculars"
  - name: "Biscuit Joiner"
  - name: "Blender"
  - name: "Blood Glucose Meter"
  - name: "Blood Pressure Monitor"
  - name: "Blower"
  - name: "Blowtorch"
  - name: "Blu-ray Player"
  - name: "Bluetooth Headset"
  - name: "Board Games"
  - name: "Boat"
  - name: "Boat Trailer"
  - name: "Boating Equipment"
  - name: "Boiler"
  - name: "Bottle Warmer"
  - name: "Bouncy Seat"
  - name: "Bread Maker"
  - name: "Breast Pump"
  - name: "Brush Cutter"
  - name: "Building Set"
  - name: "Burner"
  - name: "Cable Box"
  - name: "Calculator"
  - name: "Caller ID Box"
  - name: "Camcorder"
  - name: "Camcorder Accessories"
  - name: "Camera Accessories"
  - name: "Camera Flash"
  - name: "Camera Lens"
  - name: "Camper"
  - name: "Camping Equipment"
  - name: "Can Opener"
  - name: "Car Amplifier"
  - name: "Car Satellite Radio System"
  - name: "Car Satellite TV System"
  - name: "Car Seat"
  - name: "Car Speaker"
  - name: "Car Stereo System"
  - name: "Car Video System"
  - name: "Carbon Monoxide Alarm"
  - name: "Card Game"
  - name: "Carpet Cleaner"
  - name: "Carrying Case"
  - name: "Cash Register"
  - name: "Cassette Player"
  - name: "Caulking Gun"
  - name: "CD Player"
  - name: "Cell Phone"
  - name: "Cell Phone Accessories"
  - name: "Chainsaw"
  - name: "Chainsaw Sharpener"
  - name: "Charcoal Grill"
  - name: "Child Tracker"
  - name: "Chipper"
  - name: "Clock"
  - name: "Clock Radio"
  - name: "Clothes Dryer"
  - name: "Coffee Grinder"
  - name: "Coffeemaker"
  - name: "Compact Excavator"
  - name: "Compact Loader"
  - name: "Computer Accessories"
  - name: "Computer Drive"
  - name: "Computer Hardware"
  - name: "Computer Keyboard"
  - name: "Computer Monitor"
  - name: "Conference Phone"
  - name: "Convection Oven"
  - name: "Cooktop"
  - name: "Cookware"
  - name: "Copier"
  - name: "Corded Headset"
  - name: "Cordless Drill"
  - name: "Cordless Sander"
  - name: "Cordless Saw"
  - name: "Cordless Telephone"
  - name: "Credit Card Machine"
  - name: "Crepe Maker"
  - name: "Crib"
  - name: "Crib Toy"
  - name: "Cross Country Skier"
  - name: "CRT Television"
  - name: "Cultivator"
  - name: "Cyclometer"
  - name: "Decking"
  - name: "Dehumidifier"
  - name: "Digital Camera"
  - name: "Digital Photo Frame"
  - name: "Digital Photo Keychain"
  - name: "Dishwasher"
  - name: "DJ Equipment"
  - name: "Doll"
  - name: "Dollhouse"
  - name: "Door"
  - name: "Double Oven"
  - name: "Drill"
  - name: "Drums"
  - name: "Dryer Accessories"
  - name: "Dust Collector"
  - name: "DVD Player"
  - name: "DVD Recorder"
  - name: "DVD VCR Combo"
  - name: "DVR"
  - name: "eBook Reader"
  - name: "Edger"
  - name: "Egg Cooker"
  - name: "Electric Cookie Press"
  - name: "Electric Garlic Roaster"
  - name: "Electric Grill"
  - name: "Electric Heater"
  - name: "Electric Pencil Sharpener"
  - name: "Electric Pet Fence"
  - name: "Electric Pressure Cooker"
  - name: "Electric Shaver"
  - name: "Electric Steamer"
  - name: "Electric Toothbrush"
  - name: "Electronic Accessory"
  - name: "Electronic Keyboard"
  - name: "Elliptical Trainer"
  - name: "Engraver"
  - name: "Espresso Maker"
  - name: "Exercise Bike"
  - name: "Fan"
  - name: "Fax Machine"
  - name: "Film Camera"
  - name: "Fire Extinguisher"
  - name: "Fire Pit"
  - name: "Fish Finder"
  - name: "Fishing Equipment"
  - name: "Fitness Electronics"
  - name: "Fitness Equipment"
  - name: "Flash Memory"
  - name: "Flat Panel Television"
  - name: "Flooring"
  - name: "Fondue Maker"
  - name: "Food Processor"
  - name: "Food Saver"
  - name: "Food Warmer"
  - name: "Freezer"
  - name: "Frozen Dessert Maker"
  - name: "Fryer"
  - name: "Furnace"
  - name: "Games"
  - name: "Garage Door Opener"
  - name: "Garbage Disposal"
  - name: "Gas Grill"
  - name: "Gas Heater"
  - name: "Glue Gun"
  - name: "GPS Receiver"
  - name: "Graphics Tablet"
  - name: "Greenhouse Kit"
  - name: "Griddle"
  - name: "Grill Accessory"
  - name: "Grinder"
  - name: "Guitar"
  - name: "Hair Care Product"
  - name: "Hair Clippers"
  - name: "Hair Dryer"
  - name: "Handheld Game System"
  - name: "Handheld TV"
  - name: "Headphones"
  - name: "Hearing Aid"
  - name: "Heart Rate Monitor"
  - name: "Heat Gun"
  - name: "Heat Pump"
  - name: "Heating System"
  - name: "High Chair"
  - name: "Hiking Equipment"
  - name: "Home Care Product"
  - name: "Home Dialysis Equipment"
  - name: "Home Gym"
  - name: "Home Safety Product"
  - name: "Home Security System"
  - name: "Home Theater Screen"
  - name: "Home Theater Server"
  - name: "Home Theater System"
  - name: "Hot Beverage Maker"
  - name: "Hot Tub"
  - name: "Humidifier"
  - name: "Hunting Equipment"
  - name: "Ice Maker"
  - name: "Ice Tea Maker"
  - name: "Impact Driver"
  - name: "Indoor Fireplace"
  - name: "Indoor Furnishings"
  - name: "Inflatable Bouncy Toy"
  - name: "Insect Control Equipment"
  - name: "Insulin Pen"
  - name: "Intercom System"
  - name: "IP Phone"
  - name: "Iron"
  - name: "Irrigation System"
  - name: "Jet Ski"
  - name: "Juicer"
  - name: "Karaoke Machine"
  - name: "Kitchen Entertainment Center"
  - name: "Kitchen Grill"
  - name: "Kitchen Utensil"
  - name: "Label Maker"
  - name: "Laminate Trimmer"
  - name: "Laminator"
  - name: "Landscape Lighting"
  - name: "Laptop"
  - name: "Laptop Docking Station"
  - name: "Laser Level"
  - name: "Laser Pointer"
  - name: "Lathe"
  - name: "Lawn Aerator"
  - name: "Lawn Mower"
  - name: "Lawn Mower Accessory"
  - name: "Lawn Sweeper"
  - name: "Life Jacket"
  - name: "Light Therapy Device"
  - name: "Log Splitter"
  - name: "Lopper"
  - name: "Marine Battery"
  - name: "Marine GPS System"
  - name: "Marine Heating System"
  - name: "Marine Instruments"
  - name: "Marine Lighting"
  - name: "Marine RADAR"
  - name: "Marine Radio"
  - name: "Marine Safety Devices"
  - name: "Marine Sanitation System"
  - name: "Meat Grinder"
  - name: "Medical Alarms"
  - name: "Metal Detector"
  - name: "Microcassette Recorder"
  - name: "Microphone"
  - name: "Microscope & Magnifier"
  - name: "Microwave Oven"
  - name: "MiniDisc Player"
  - name: "Mixer"
  - name: "Mobility Aid"
  - name: "Mobility Scooter"
  - name: "Model Vehicle"
  - name: "Modem"
  - name: "Motor Scooter"
  - name: "Motorcycle"
  - name: "Motorcycle Accessories"
  - name: "Motorized Awning"
  - name: "Motorized Toy Car"
  - name: "Mouse"
  - name: "MP3 Docking Station"
  - name: "MP3 Player"
  - name: "MP3 Player Accessories"
  - name: "Multi-tool"
  - name: "Music Mixer"
  - name: "Music Pedal"
  - name: "Musical Instrument"
  - name: "Musical Instrument Amplifier"
  - name: "Musical Table"
  - name: "Musical Toy Instrument"
  - name: "Nail Gun"
  - name: "Nebulizer"
  - name: "Network Cables"
  - name: "Network Card"
  - name: "Network Hardware"
  - name: "Network Router"
  - name: "Noise Reduction Machine"
  - name: "Offroad Vehicle"
  - name: "Outboard Motor"
  - name: "Outdoor Cart"
  - name: "Outdoor Ceiling Fan"
  - name: "Outdoor Fireplace"
  - name: "Outdoor Fountain"
  - name: "Outdoor Gas Burner"
  - name: "Outdoor Grill Cover"
  - name: "Outdoor Kitchen Island"
  - name: "Outdoor Misting Fan"
  - name: "Outdoor Shower"
  - name: "Outdoor Storage"
  - name: "Outdoor Timer"
  - name: "Oven"
  - name: "Oven Accessories"
  - name: "Oxygen Equipment"
  - name: "Pacemaker"
  - name: "Pager"
  - name: "Paint Remover"
  - name: "Paint Sprayer"
  - name: "Paper Shredder"
  - name: "Pasta Maker"
  - name: "Patio Furniture"
  - name: "Patio Heater"
  - name: "Patio Umbrella"
  - name: "PDAs & Smartphones"
  - name: "Pedicure Spa"
  - name: "Personal Computer"
  - name: "Personal Lift"
  - name: "Pest Control Equipment"
  - name: "Pet Care Product"
  - name: "Pet Fence"
  - name: "Photo Printer"
  - name: "Photo Scanner"
  - name: "Picnic Table"
  - name: "Pill Reminder Device"
  - name: "Planer"
  - name: "Plumbing Product"
  - name: "Pole Saw"
  - name: "Popcorn Poppers"
  - name: "Portable CD Player"
  - name: "Portable DVD Player"
  - name: "Portable Generator"
  - name: "Portable Media Storage"
  - name: "Portable Multimedia Player"
  - name: "Portable Radio"
  - name: "Portable Speaker"
  - name: "Portable Stereo System"
  - name: "Postal Equipment"
  - name: "Power Hammer"
  - name: "Power Roller"
  - name: "Power Screwdriver"
  - name: "Power Supply"
  - name: "Pressure Washer"
  - name: "Printer"
  - name: "Printer Accessories"
  - name: "Projection Television"
  - name: "Projector"
  - name: "Projector Accessories"
  - name: "Quesadilla Maker"
  - name: "Radar Detector"
  - name: "Radio"
  - name: "Radio Antenna"
  - name: "Range"
  - name: "Recording Equipment"
  - name: "Refrigerator"
  - name: "Remote Starter"
  - name: "Respiratory Product"
  - name: "Rice Cooker"
  - name: "Riding Toy"
  - name: "Robotics"
  - name: "Router"
  - name: "Rowing Machine"
  - name: "Safety Gate"
  - name: "Sander"
  - name: "Satellite Radio"
  - name: "Satellite TV System"
  - name: "Saw"
  - name: "Scale"
  - name: "Scanner"
  - name: "Scuba Diving Equipment"
  - name: "Security Camera"
  - name: "Septic System"
  - name: "Server"
  - name: "Sewing Machine"
  - name: "Siding"
  - name: "Skin Care Product"
  - name: "Skis"
  - name: "Sleep Apnea Machine"
  - name: "Slow Cooker"
  - name: "Smoke Alarm"
  - name: "Smoker"
  - name: "Snow Blower"
  - name: "Snow Blower Attachment"
  - name: "Snowboard"
  - name: "Snowshoes"
  - name: "Soldering Gun"
  - name: "SONAR"
  - name: "Speaker"
  - name: "Speaker System"
  - name: "Spreader"
  - name: "Sprinkler"
  - name: "Staple Gun"
  - name: "Stepper Machine"
  - name: "Stereo Amplifier"
  - name: "Stereo Equalizer"
  - name: "Stereo Receiver"
  - name: "Stereo System"
  - name: "Stove"
  - name: "Stroller"
  - name: "Stud Sensor"
  - name: "Styling Iron"
  - name: "Surge Protector"
  - name: "Swimming Pool"
  - name: "Swimming Pool Filter"
  - name: "Swimming Pool Gate Alarm"
  - name: "Swimming Pool Heater"
  - name: "Swimming Pool Pump"
  - name: "Swimming Pool Vacuum"
  - name: "Swing Sets"
  - name: "Switch"
  - name: "Table Top Game"
  - name: "Tablet"
  - name: "Tablet Accessory"
  - name: "Telephone"
  - name: "Telephone Accessories"
  - name: "Telescope"
  - name: "Tent"
  - name: "Thermometer"
  - name: "Thermostat"
  - name: "Tiller"
  - name: "Time Clock"
  - name: "Toaster"
  - name: "Toddler Furniture"
  - name: "Tool Storage"
  - name: "Tortilla Maker"
  - name: "Trash Compactor"
  - name: "Treadmill"
  - name: "Trimmer"
  - name: "Turkey Fryer"
  - name: "Turntable"
  - name: "TV Antenna"
  - name: "TV Cables"
  - name: "TV Converter Box"
  - name: "TV DVD Combo"
  - name: "TV Mount"
  - name: "TV Receiver"
  - name: "TV VCR Combo"
  - name: "TV Video Accessories"
  - name: "Two-Way Radio"
  - name: "Typewriter"
  - name: "Ultrasonic Jewelry Cleaner"
  - name: "Universal Remote"
  - name: "Utility Trailer"
  - name: "Utility Vehicle"
  - name: "Vacuum Cleaner"
  - name: "VCR"
  - name: "Ventilation Hood"
  - name: "Video Eyeware"
  - name: "Video Game Console"
  - name: "Video Game Controller"
  - name: "Video Game Furniture"
  - name: "Video Game Headset"
  - name: "Video Game Keyboard"
  - name: "Video Game Sound System"
  - name: "Video Games"
  - name: "Video Gaming Accessories"
  - name: "Waffle Iron"
  - name: "Washer"
  - name: "Washer Accessories"
  - name: "Washer/Dryer"
  - name: "Watch"
  - name: "Water Dispenser"
  - name: "Water Heater"
  - name: "Water Pump"
  - name: "Water System"
  - name: "Waterskis"
  - name: "Weather Radio"
  - name: "Webcam"
  - name: "Welder"
  - name: "Welding Consumables"
  - name: "Welding System"
  - name: "Wheelchair"
  - name: "Whiteboard Accessories"
  - name: "Window"
  - name: "Wireless Office Headset"
  - name: "Wok"
  - name: "Work Light"
  - name: "Yard Vacuum"
  - name: "Yogurt Maker"

given:
  - "Audio System"
  - "Air Conditioner"
  - "Radio"
  - "Stove"
  - "Tablet"
  - "Fridge"
  - "Freezer"
  - "Microwave"
  - "Juicer"
  - "Toaster"
  - "Oven"
  - "Kettle"
  - "Electric Cooker"
  - "Coffee Machine"
  - "Mixer"
  - "Food Processor"
  - "Scanner"
  - "Projector"

matching:
  "Microwave":
    - "Microwave Oven"
  "Fridge":
    - "Refrigerator"
  "Coffee Machine":
    - "Coffeemaker"

